baseURL: "https://reside-ic.github.io/wodin-news/"
languageCode: "en-gb"
title: "Wodin News"
theme: ["papermod-changelog", "PaperMod"]
enableEmoji: true

params:
  # https://github.com/adityatelange/hugo-PaperMod/wiki/Installation#sample-configyml
  DateFormat: "2 Jan 2006"
  disableThemeToggle: true
  disableSpecial1stPost: true
  hideMeta: false
  ShowPostNavLinks: true
  homeInfoParams:
    Title: Wodin News
    Content: What's new and updated in Wodin
  tags:
    - text: Update
      colour: "#FFBA11"
    - text: Feature
      colour: "#14CC80"
    - text: App
      colour: "#E31837"

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: epimodels
      name: EpiModels
      url: https://epimodels.dide.ic.ac.uk
      weight: 30
